name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  INSTANCE_MEMORY: ${{ secrets.INSTANCE_MEMORY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Build with Gradle
        run: ./gradlew build jib --stacktrace

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE }} \
            --image "gcr.io/${{ secrets.GCP_PROJECT }}/countries-image" \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --max-instances ${{ secrets.INSTANCE_MAX }} \
            --memory ${{ secrets.INSTANCE_MEMORY }}Mi \
            --concurrency ${{ secrets.CONCURRENCY_MAX }} \
            --set-env-vars SPRING_DATA_MONGODB_DATABASE=${{ secrets.SPRING_DATA_MONGODB_DATABASE }},SPRING_DATA_MONGODB_USERNAME=${{ secrets.SPRING_DATA_MONGODB_USERNAME }},SPRING_DATA_MONGODB_PASSWORD=${{ secrets.SPRING_DATA_MONGODB_PASSWORD }},SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}
